---
- name: k8s Pod
  hosts: all
  become: yes
  user: mikey
  tasks:
    - name: create a Pod
      command: kubectl apply -f mikey-pod.yaml

    - name: create a Service
      command: kubectl apply -f mikey-service.yaml