---
- name: k8s Pod
  hosts: all
  become: yes
  user: arn:aws:eks:us-east-2:054561636315:cluster/education-eks-nGDnvDh9
  tasks:
    - name: create a Pod
      command: /home/mikey/bin/kubectl apply -f /home/mikey/mikey-pod.yaml

    - name: create a Service
      command: /home/mikey/bin/kubectl apply -f /home/mikey/mikey-service.yaml