- name: k8s Pod
  hosts: all
  become: yes
  tasks:
    - name: create a Pod
      command: /home/mikey/kubectl apply -f /opt/kubernetes/mikey-pod.yaml
    - name: create a Service
      command: /home/mikey/kubectl apply -f /opt/kubernetes/mikey-service.yaml