apiVersion: v1
kind: Pod
metadata:
  name: mikey-pod
  labels:
    app: gameoflife
spec:
  containers:
    - name: mikey-container
      image: mike8309/mikey:1.0
      ports:
        - containerPort: 8080
          protocol: TCP