---
- name: k8s Pod
  hosts: all
  become: yes
  tasks:
    - name: create a Pod
      command: kubectl apply -f /home/mikey/opt/kubernetes/mikey-pod.yaml

    - name: create a Service
      command: kubectl apply -f /home/mikey/opt/kubernetes/mikey-service.yaml