---
- name: create a container
  hosts: all
  become: yes
  tasks:
    - name: pull the image
      command: docker image pull mike8309/mikey:1.0
      
    - name: create a container
      command: docker container run -d --name mikey -p 8081:8080 mike8309/mikey:1.0