---
- name: k8s Pod
  hosts: all
  become: yes
  tasks:
    - name: create a Pod
      command: kubectl apply -f ~/learn-terraform-provision-eks-cluster/mikey-pod.yaml

    - name: create a Service
      command: kubectl apply -f ~/learn-terraform-provision-eks-cluster/mikey-service.yaml