---
- name: k8s Pod
  hosts: all
  become: yes
  tasks:
    - name: create a Pod
      command: kubectl apply -f mikey-pod.yaml
      args:
        chdir: /opt/kubernetes

    - name: create a Service
      command: kubectl apply -f mikey-service.yaml
      args:
        chdir: /opt/kubernetes