---
- name: k8s Pod
  hosts: all
  become: yes
  tasks:
    - name: create a Pod
      command: kubectl apply -f /home/mikey/mikey-pod.yaml
      args:
        chdir: /home/mikey

    - name: create a Service
      command: kubectl apply -f /home/mikey/mikey-service.yaml
      args:
        chdir: /home/mikey